// ---------------------------------------------------------------------------
// Install REST Client extension for VS Code to use this file:
// https://marketplace.visualstudio.com/items?itemName=humao.rest-client
// ---------------------------------------------------------------------------

http://localhost:3030/scores

###

POST http://localhost:3030/scores
Content-Type: application/json

{
  "playerId": 1,
  "score": 123
}
